import React, { useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { userApi } from '../../api/user.api'
import { orderApi } from '../../api/order.api'
import { useCart } from '../../hooks/useCart'
import { useAuthStore } from '../../store/auth.store'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import * as zod from 'zod'
import {
  MapPin,
  CreditCard,
  Truck,
  ArrowLeft,
  Loader2,
  Plus,
  Home,
  Briefcase,
  AlertCircle,
} from 'lucide-react'
import { toast } from 'react-hot-toast'

const addressSchema = zod.object({
  label: zod.string().min(2, 'Label is required (e.g. Home, Work)'),
  addressLine: zod.string().min(5, 'Full address line is required'),
  city: zod.string().min(2, 'City is required'),
  state: zod.string().min(2, 'State is required'),
  pincode: zod.string().length(6, 'Pincode must be exactly 6 digits').regex(/^\d+$/, 'Pincode must contain only numbers'),
})

type AddressInputs = zod.infer<typeof addressSchema>;

export const CheckoutPage: React.FC = () => {
  const navigate = useNavigate()
  const queryClient = useQueryClient()
  const { user } = useAuthStore()
  const { cart, clearCart } = useCart()

  const [selectedAddressId, setSelectedAddressId] = useState<number | null>(null)
  const [paymentMethod, setPaymentMethod] = useState<'CARD' | 'UPI' | 'COD'>('CARD')
  const [showAddressForm, setShowAddressForm] = useState(false)
  const [isPlacingOrder, setIsPlacingOrder] = useState(false)

  // Fetch addresses
  const { data: addresses, isLoading: isAddressesLoading } = useQuery({
    queryKey: ['addresses'],
    queryFn: async () => {
      const data = await userApi.getAddresses()
      // Set default address if available
      const def = data.find((addr) => addr.isDefault)
      if (def) {
        setSelectedAddressId(def.id)
      } else if (data.length > 0) {
        setSelectedAddressId(data[0].id)
      }
      return data
    },
  })

  // Add Address mutation
  const { register, handleSubmit, reset, formState: { errors: formErrors } } = useForm<AddressInputs>({
    resolver: zodResolver(addressSchema),
  })

  const addAddressMutation = useMutation({
    mutationFn: (data: AddressInputs) =>
      userApi.addAddress({
        ...data,
        lat: 12.9716, // Default to Bangalore lat
        lng: 77.5946, // Default to Bangalore lng
        isDefault: addresses?.length === 0, // Default if first address
      }),
    onSuccess: (newAddr) => {
      queryClient.invalidateQueries({ queryKey: ['addresses'] })
      setSelectedAddressId(newAddr.id)
      setShowAddressForm(false)
      reset()
      toast.success('Address added successfully!')
    },
    onError: (err: any) => {
      toast.error(err.response?.data?.message || 'Failed to add address')
    },
  })

  const handleAddAddress = (data: AddressInputs) => {
    addAddressMutation.mutate(data)
  }

  // Handle Order Placement
  const handlePlaceOrder = async () => {
    if (isPlacingOrder) return
    if (!selectedAddressId) {
      toast.error('Please select a delivery address')
      return
    }

    if (!cart || cart.items.length === 0) {
      toast.error('Your cart is empty')
      return
    }

    setIsPlacingOrder(true)

    try {
      // 1. Initiate order on backend
      const orderInitiate = await orderApi.initiateOrder({
        addressId: selectedAddressId,
        paymentMethod: paymentMethod === 'COD' ? 'COD' : 'ONLINE',
        couponCode: cart.couponCode,
      })

      // 2. COD Payment Flow
      if (paymentMethod === 'COD') {
        toast.success('Order placed successfully (Cash on Delivery)!')
        await clearCart()
        setIsPlacingOrder(false)
        navigate(`/orders/${orderInitiate.id}/track`)
        return
      }

      // 3. Online Razorpay Payment Flow
      if (!orderInitiate.razorpayOrderId) {
        throw new Error('Razorpay Order ID was not generated by backend')
      }

      const rzKey = import.meta.env.VITE_RAZORPAY_KEY_ID || 'rzp_test_XXXX'

      const rzOptions = {
        key: rzKey,
        amount: orderInitiate.totalAmount * 100, // paise
        currency: 'INR',
        name: 'EETS Food Delivery',
        description: `Payment for Order #${orderInitiate.orderNumber}`,
        order_id: orderInitiate.razorpayOrderId,
        handler: async function (response: any) {
          try {
            // Verify payment on backend
            await orderApi.verifyPayment({
              razorpayOrderId: orderInitiate.razorpayOrderId!,
              razorpayPaymentId: response.razorpay_payment_id,
              razorpaySignature: response.razorpay_signature,
              orderId: orderInitiate.id,
            })
            toast.success('Payment verified! Order placed.')
            await clearCart()
            navigate(`/orders/${orderInitiate.id}/track`)
          } catch (verifyError: any) {
            toast.error(verifyError.response?.data?.message || 'Payment verification failed. Please contact support.')
          } finally {
            setIsPlacingOrder(false)
          }
        },
        prefill: {
          name: user?.name || '',
          email: user?.email || '',
          contact: user?.phone || '',
        },
        theme: {
          color: '#0d9488',
        },
        modal: {
          ondismiss: function () {
            toast.error('Payment cancelled')
            setIsPlacingOrder(false)
          },
        },
      }

      const razorpay = new (window as any).Razorpay(rzOptions)
      razorpay.open()
    } catch (err: any) {
      toast.error(err.response?.data?.message || err.message || 'Failed to place order')
      setIsPlacingOrder(false)
    }
  }

  if (!cart || cart.items.length === 0) {
    return (
      <div className="max-w-md mx-auto text-center py-20 px-4">
        <AlertCircle className="w-16 h-16 text-primary mx-auto mb-4 stroke-1" />
        <h3 className="font-heading text-lg font-bold text-textMain">No Checkout Items</h3>
        <p className="text-sm text-mutedColor mt-1">Please add items to your cart before proceeding.</p>
        <Link to="/" className="mt-6 inline-flex bg-primary hover:bg-primary-hover text-white px-5 py-2.5 rounded-xl text-sm font-bold shadow-sm">
          Go Back Home
        </Link>
      </div>
    )
  }

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
      <Link
        to="/cart"
        className="inline-flex items-center gap-1.5 text-sm font-bold text-mutedColor hover:text-primary transition-colors mb-8"
      >
        <ArrowLeft className="w-4 h-4" />
        <span>Return to Cart</span>
      </Link>

      <h1 className="font-heading text-3xl font-extrabold text-textMain mb-8">Checkout</h1>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 items-start">
        {/* Left Column: Delivery address & Payment selection */}
        <div className="lg:col-span-2 space-y-6">
          {/* Address selector */}
          <div className="bg-white border border-gray-100 shadow-sm rounded-2xl p-6">
            <div className="flex items-center justify-between mb-6">
              <h3 className="font-heading font-bold text-textMain text-lg flex items-center gap-2">
                <MapPin className="w-5 h-5 text-primary" />
                <span>Delivery Address</span>
              </h3>
              {!showAddressForm && (
                <button
                  onClick={() => setShowAddressForm(true)}
                  type="button"
                  className="flex items-center gap-1 text-xs text-primary font-bold hover:underline"
                >
                  <Plus className="w-4.5 h-4.5" />
                  <span>Add New</span>
                </button>
              )}
            </div>

            {isAddressesLoading ? (
              <div className="flex items-center gap-2 py-4">
                <Loader2 className="w-4 h-4 animate-spin text-primary" />
                <span className="text-xs text-mutedColor font-semibold">Loading addresses...</span>
              </div>
            ) : showAddressForm ? (
              /* Inline Address Form */
              <form onSubmit={handleSubmit(handleAddAddress)} className="space-y-4 border-t border-gray-50 pt-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-xs font-semibold text-textMain mb-1">Label</label>
                    <input
                      type="text"
                      placeholder="Home, Work, etc."
                      {...register('label')}
                      className="w-full px-3.5 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent text-sm text-textMain"
                    />
                    {formErrors.label && (
                      <p className="text-xs text-error mt-0.5 font-medium">{formErrors.label.message}</p>
                    )}
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-textMain mb-1">Pincode</label>
                    <input
                      type="text"
                      placeholder="560001"
                      maxLength={6}
                      {...register('pincode')}
                      className="w-full px-3.5 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent text-sm text-textMain"
                    />
                    {formErrors.pincode && (
                      <p className="text-xs text-error mt-0.5 font-medium">{formErrors.pincode.message}</p>
                    )}
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-semibold text-textMain mb-1">Address Details</label>
                  <input
                    type="text"
                    placeholder="House No, Building, Street Name..."
                    {...register('addressLine')}
                    className="w-full px-3.5 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent text-sm text-textMain"
                  />
                  {formErrors.addressLine && (
                    <p className="text-xs text-error mt-0.5 font-medium">{formErrors.addressLine.message}</p>
                  )}
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-xs font-semibold text-textMain mb-1">City</label>
                    <input
                      type="text"
                      placeholder="Bangalore"
                      {...register('city')}
                      className="w-full px-3.5 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent text-sm text-textMain"
                    />
                    {formErrors.city && (
                      <p className="text-xs text-error mt-0.5 font-medium">{formErrors.city.message}</p>
                    )}
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-textMain mb-1">State</label>
                    <input
                      type="text"
                      placeholder="Karnataka"
                      {...register('state')}
                      className="w-full px-3.5 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent text-sm text-textMain"
                    />
                    {formErrors.state && (
                      <p className="text-xs text-error mt-0.5 font-medium">{formErrors.state.message}</p>
                    )}
                  </div>
                </div>

                <div className="flex justify-end gap-2 pt-2">
                  <button
                    onClick={() => {
                      setShowAddressForm(false)
                      reset()
                    }}
                    type="button"
                    className="px-4 py-2 border border-gray-200 hover:bg-gray-50 rounded-lg text-xs font-bold text-mutedColor transition-colors"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    disabled={addAddressMutation.isPending}
                    className="bg-primary hover:bg-primary-hover text-white px-4 py-2 rounded-lg text-xs font-bold transition-colors shadow-sm disabled:opacity-50"
                  >
                    Save Address
                  </button>
                </div>
              </form>
            ) : addresses && addresses.length > 0 ? (
              /* Address List selector */
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {addresses.map((addr) => {
                  const isSelected = selectedAddressId === addr.id
                  return (
                    <div
                      key={addr.id}
                      onClick={() => setSelectedAddressId(addr.id)}
                      className={`p-4 rounded-xl border-2 cursor-pointer transition-all flex gap-3 relative ${
                        isSelected
                          ? 'border-primary bg-primary-light/30'
                          : 'border-gray-100 bg-white hover:bg-gray-50'
                      }`}
                    >
                      <div className="text-primary mt-0.5 flex-shrink-0">
                        {addr.label.toLowerCase() === 'home' ? (
                          <Home className="w-5 h-5" />
                        ) : (
                          <Briefcase className="w-5 h-5" />
                        )}
                      </div>
                      <div className="text-sm">
                        <span className="font-bold text-textMain capitalize block mb-0.5">
                          {addr.label}
                        </span>
                        <p className="text-xs text-mutedColor leading-relaxed line-clamp-2">
                          {addr.addressLine}, {addr.city}, {addr.state} - {addr.pincode}
                        </p>
                      </div>
                    </div>
                  )
                })}
              </div>
            ) : (
              <div className="text-center py-6 border-2 border-dashed border-gray-200 rounded-xl">
                <p className="text-sm text-mutedColor mb-4">No saved addresses found.</p>
                <button
                  onClick={() => setShowAddressForm(true)}
                  type="button"
                  className="bg-primary hover:bg-primary-hover text-white px-4 py-2 rounded-xl text-xs font-bold shadow-sm"
                >
                  Create Your First Address
                </button>
              </div>
            )}
          </div>

          {/* Payment selector */}
          <div className="bg-white border border-gray-100 shadow-sm rounded-2xl p-6">
            <h3 className="font-heading font-bold text-textMain text-lg flex items-center gap-2 mb-6">
              <CreditCard className="w-5 h-5 text-primary" />
              <span>Select Payment Method</span>
            </h3>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              {/* Card (Razorpay) */}
              <div
                onClick={() => setPaymentMethod('CARD')}
                className={`p-4 rounded-xl border-2 cursor-pointer transition-all text-center flex flex-col items-center gap-2 ${
                  paymentMethod === 'CARD'
                    ? 'border-primary bg-primary-light/30'
                    : 'border-gray-100 bg-white hover:bg-gray-50'
                }`}
              >
                <CreditCard className="w-6 h-6 text-primary" />
                <span className="text-sm font-bold text-textMain">Credit/Debit Card</span>
                <span className="text-[10px] text-mutedColor font-semibold">Razorpay Secure</span>
              </div>

              {/* UPI */}
              <div
                onClick={() => setPaymentMethod('UPI')}
                className={`p-4 rounded-xl border-2 cursor-pointer transition-all text-center flex flex-col items-center gap-2 ${
                  paymentMethod === 'UPI'
                    ? 'border-primary bg-primary-light/30'
                    : 'border-gray-100 bg-white hover:bg-gray-50'
                }`}
              >
                <svg className="w-6 h-6 text-primary fill-current" viewBox="0 0 24 24">
                  <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-6h2v6zm0-8h-2V7h2v2z" />
                </svg>
                <span className="text-sm font-bold text-textMain">UPI Payment</span>
                <span className="text-[10px] text-mutedColor font-semibold">GPay/PhonePe/Paytm</span>
              </div>

              {/* Cash on Delivery */}
              <div
                onClick={() => setPaymentMethod('COD')}
                className={`p-4 rounded-xl border-2 cursor-pointer transition-all text-center flex flex-col items-center gap-2 ${
                  paymentMethod === 'COD'
                    ? 'border-primary bg-primary-light/30'
                    : 'border-gray-100 bg-white hover:bg-gray-50'
                }`}
              >
                <Truck className="w-6 h-6 text-primary" />
                <span className="text-sm font-bold text-textMain">Cash on Delivery</span>
                <span className="text-[10px] text-mutedColor font-semibold">Pay cash at door</span>
              </div>
            </div>
          </div>
        </div>

        {/* Right Column: Order summary breakdown */}
        <div className="bg-white border border-gray-100 shadow-sm rounded-2xl p-6">
          <h3 className="font-heading font-bold text-textMain text-base mb-4 border-b border-gray-50 pb-3">
            Order Summary
          </h3>

          <div className="divide-y divide-gray-50 mb-6 max-h-48 overflow-y-auto">
            {cart.items.map((item) => (
              <div key={item.id} className="py-2.5 flex justify-between text-xs">
                <div>
                  <span className="font-bold text-textMain block">{item.name}</span>
                  <span className="text-mutedColor mt-0.5 block">Quantity: {item.quantity}</span>
                </div>
                <span className="font-bold text-textMain">₹{item.price * item.quantity}</span>
              </div>
            ))}
          </div>

          <div className="space-y-3 text-xs mb-6 border-t border-gray-50 pt-4">
            <div className="flex justify-between text-mutedColor">
              <span>Item Subtotal</span>
              <span className="font-semibold text-textMain">₹{cart.subtotal}</span>
            </div>

            {cart.discountAmount > 0 && (
              <div className="flex justify-between text-emerald-700 font-medium">
                <span>Coupon Applied</span>
                <span>-₹{cart.discountAmount}</span>
              </div>
            )}

            <div className="flex justify-between text-mutedColor">
              <span>Delivery Charges</span>
              <span className="font-semibold text-textMain">₹{cart.deliveryFee}</span>
            </div>

            <div className="flex justify-between text-mutedColor">
              <span>Taxes and Fees</span>
              <span className="font-semibold text-textMain">₹{cart.taxAmount}</span>
            </div>

            <div className="flex justify-between text-sm font-bold text-textMain border-t border-gray-100 pt-3 mt-3">
              <span>To Pay</span>
              <span className="text-primary text-base">₹{cart.totalAmount}</span>
            </div>
          </div>

          <button
            onClick={handlePlaceOrder}
            disabled={isPlacingOrder || !selectedAddressId}
            className="hidden sm:flex w-full bg-primary hover:bg-primary-hover text-white py-3.5 px-4 rounded-xl text-sm font-bold shadow-sm items-center justify-center gap-2 transition-colors disabled:opacity-50"
          >
            {isPlacingOrder ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                <span>Processing Order...</span>
              </>
            ) : (
              <span>Place Order</span>
            )}
          </button>
        </div>
      </div>

      {/* Mobile Sticky Bottom Place Order Strip */}
      <div className="sm:hidden fixed bottom-16 left-0 right-0 bg-white border-t border-slate-100 p-4 z-30 shadow-[0_-4px_12px_rgba(0,0,0,0.05)] flex items-center justify-between">
        <div className="flex flex-col">
          <span className="text-[10px] text-mutedColor font-bold uppercase tracking-wider">Total to Pay</span>
          <span className="text-lg font-heading font-extrabold text-primary">₹{cart.totalAmount}</span>
        </div>
        <button
          onClick={handlePlaceOrder}
          disabled={isPlacingOrder || !selectedAddressId}
          className="bg-primary hover:bg-primary-hover text-white font-bold px-5 py-2.5 rounded-xl text-xs flex items-center gap-1.5 shadow-sm transition-colors disabled:opacity-50"
        >
          {isPlacingOrder ? (
            <Loader2 className="w-4 h-4 animate-spin" />
          ) : (
            <span>Place Order</span>
          )}
        </button>
      </div>
    </div>
  )
}
export default CheckoutPage
